### ISSUE TITLE
Add BTP litepaper to site

### ISSUE THREAD

**Issue by han-so1omon** [icon-community/icon.community#12]
Similar to on the Ethereum docs, I recommend to add it to the `Resources->` section of the header and the footer

**Comment by han-so1omon** [comment]
@bwhli Do you have the bandwidth to do this in the next week or so?

**Comment by bwhli** [comment]
Yes, I can add it.

**Comment by han-so1omon** [comment]
@bwhli Thank you!

**Comment by bwhli** [comment]
Just added this.

**Comment by han-so1omon** [comment]
Thank you!
