### ISSUE TITLE
Careers page

### ISSUE THREAD

**Issue by han-so1omon** [icon-community/icon.community#13]
Add a careers page with a similar format to the following examples:
- https://www.bloxbean.com/contact/
- https://www.valvesoftware.com/en/jobs?job_id=14

Goal is _not_ to hire. Goal is to see what people are sending in with interest

**Comment by bwhli** [comment]
@han-so1omon If there isn't a need to list actual roles, can we just set up a Typeform page and have a "Careers" button that just links to it for the time being? The website is static, so we don't have a server to handle submissions from an on-page form. Can set up some kind of service to receive form submission and forward it to an ICON email, but if we're doing that, we might as well just use a dedicated form service like Typeform. If that's okay, I'll have David set up a form and add the link to it.

**Comment by han-so1omon** [comment]
That sounds good to me, but please send me the form before we publish it so that we can agree on it's structure and copytext
