### ISSUE TITLE
BTP integrations image not dynamically resizing

### ISSUE THREAD

**Issue by tjhunt1** [icon-community/icon.community#14]
iPhone 7 mobile

![image](https://user-images.githubusercontent.com/98855020/184041951-36403244-1645-45b1-8fe8-1375951d34e6.png)

**Comment by rhizome-labs** [comment]
> iPhone 7 mobile
> 
> ![image](https://user-images.githubusercontent.com/98855020/184041951-36403244-1645-45b1-8fe8-1375951d34e6.png)

@tjhunt1 This isn't a bug, but it's not ideal. The HTML/CSS component we used was structured like this. A few people have mentioned this, but I haven't had time to change it (takes me a long time to do frontend stuff because I'm not a frontend dev).

**Comment by tjhunt1** [comment]
Perfect - I can close then since you are aware 👌
