### ISSUE TITLE
APY, ICX Price and Market Cap on the main page doesn't load

### ISSUE THREAD

**Issue by VadymEverstake** [icon-community/icon.community#81]
**Describe the bug**
The fields for APY, ICX Price and Market Cap on the main page of the website don't show any information.
1. Go to main page
2. Scroll down to the described above area
3.  See that there is no info

**Expected behavior**
To see this data on the website again
**Screenshots**
![image](https://user-images.githubusercontent.com/122529596/212067658-e11f4e1d-be9b-4bd3-a633-b06a5bc00a3e.png)

**Desktop (please complete the following information):**
 - Chrome Browser

**Comment by DavidFBD** [comment]
Brought back price and market cap. Removed staking apy for the time being.

**Comment by VadymEverstake** [comment]
Thanks! May I ask why apy is currently removed? Will it be back any time soon?
